import Head from "next/head";
import Image from "next/image";
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import { Carousel } from "react-responsive-carousel";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ahuja Sweets - Sweet is life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel swipeable autoPlay emulateTouch infiniteLoop useKeyboardArrows>
        <div>
          <img width={1920} height={1200} src="/burger.jpg" />
          <Link href="/categories/burger">
            <a>
              <p className="legend"> Chicken Grand Burger</p>
            </a>
          </Link>
        </div>
        <div>
          <img width={1920} height={1200} src="/pizza.jpg" />
          <Link href="/categories/pizza">
            <a>
              <p className="legend">Onion Grill Pizza</p>
            </a>
          </Link>
        </div>
        <div>
          <img width={1920} height={1200} src="/chicken.jpg" />
          <Link href="/categories/italian">
            <a>
              <p className="legend"> Spicy Chicken Sticks</p>
            </a>
          </Link>
        </div>
      </Carousel>

      <section className="text-gray-600 body-font -m-8">
        <div className="container px-5 py-16 mx-auto">
          <div className="flex flex-wrap justify-center -m-4">
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                  >
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2 text-center">
                  Good Services
                </h2>
                <p className="leading-relaxed text-base text-center">
                  All kinds of best services!!
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                  >
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2 text-center">
                  Reasonable Price
                </h2>
                <p className="leading-relaxed text-base text-center">
                  A pocket friendly restaurent!!
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                  >
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2 text-center">
                  Tasty Food
                </h2>
                <p className="leading-relaxed text-base text-center">
                  You will surely lick your fingers after eating!!
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="text-gray-600 body-font -mt-12">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap w-full">
            <div className="lg:w-1/2 w-full mb-6 lg:mb-0">
              <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
                Our Best Food Items
              </h1>
              <div className="h-1 w-20 bg-indigo-500 rounded"></div>
            </div>
            <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">
              Try our best and most selling food items.
            </p>
          </div>
          <div className="flex flex-wrap">
            <div className="lg:w-2/12 h-full lg:mr-10 md:w-1/2 p-4 w-full shadow-lg transform transition duration-500 hover:scale-105">
              <div className="block relative rounded overflow-hidden">
                <img
                  alt="ecommerce"
                  className="m-auto md:m-0 object-cover object-center w-full h-full block"
                  src="https://images.unsplash.com/photo-1613564834361-9436948817d1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=443&q=80"
                />
              </div>
              <div className="mt-4">
                <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">
                  Pizza
                </h3>
                <h2 className="text-gray-900 title-font text-lg font-medium">
                  Onion Grill Pizza
                </h2>
                <p className="mt-1">₹250/ps</p>
                <button className="flex mx-auto mt-3 text-white bg-amber-500 border-0 py-1 px-4 focus:outline-none hover:bg-amber-600 rounded text-lg">
                  Add to Cart
                </button>
              </div>
            </div>
            <div className="lg:w-2/12 h-full lg:mr-10 md:w-1/2 p-4 w-full shadow-lg transform transition duration-500 hover:scale-105 mt-5">
              <div className="block relative rounded overflow-hidden">
                <img
                  alt="ecommerce"
                  className="m-auto md:m-0 object-cover object-center w-full h-full block"
                  src="https://images.unsplash.com/photo-1521305916504-4a1121188589?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1780&q=80"
                />
              </div>
              <div className="mt-4">
                <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">
                  Burger
                </h3>
                <h2 className="text-gray-900 title-font text-lg font-medium">
                  Chicken Grand Burger
                </h2>
                <p className="mt-1">₹120/ps</p>
                <button className="flex mx-auto mt-3 text-white bg-amber-500 border-0 py-1 px-4 focus:outline-none hover:bg-amber-600 rounded text-lg">
                  Add to Cart
                </button>
              </div>
            </div>
            <div className="lg:w-2/12 lg:mr-10 md:w-1/2 p-4 w-full shadow-lg transform transition duration-500 hover:scale-105 mt-5">
              <div className="block relative rounded overflow-hidden">
                <img
                  alt="ecommerce"
                  className="m-auto md:m-0 object-cover object-center w-full h-full block"
                  src="https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bm9vZGxlc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60"
                />
              </div>
              <div className="mt-4">
                <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">
                  Noodles
                </h3>
                <h2 className="text-gray-900 title-font text-lg font-medium">
                  Veg Hakka Noodles
                </h2>
                <p className="mt-1">₹70/bowl</p>
                <button className="flex mx-auto mt-3 text-white bg-amber-500 border-0 py-1 px-4 focus:outline-none hover:bg-amber-600 rounded text-lg">
                  Add to Cart
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
